### ISSUE TITLE
Fix batch mul issue that appears in recursive merge verifier

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#1024]
The Ultra arithmetized recursive merge verifier circuit fails due (I think) to a quirk in the Ultra batch mul. Reproduce this in a minimal test to diagnose then resolve.

**Comment by Rumata888** [comment]
Can be fixed now with with_edgecases argument https://github.com/AztecProtocol/barretenberg/blob/43cfa7b3d1ee1bf404e2a086b7e9589cc73eaa66/cpp/src/barretenberg/stdlib/primitives/biggroup/biggroup_impl.hpp#L786
