### ISSUE TITLE
Input univariates in the Sumcheck Relations

### ISSUE THREAD

**Issue by arijitdutta67** [AztecProtocol/barretenberg#118]
The sum check code should panic if the  Input univariates in the sumcheck relations are not linear polynomials.

**Comment by codygunton** [comment]
As we discussed in scrum, you are referring to something that would happen inside of a relation's `add_edge_contribution` function, but the performance of these functions is critical, so we cannot tolerate any additional overhead. The more particular concern is to prevent https://github.com/AztecProtocol/barretenberg/blob/2773c5f10bbae5dbd5bd6ff3a830d5513def8b8d/cpp/src/aztec/honk/sumcheck/relations/relation.test.cpp#L105 from being defined in such a way that the array elements are not in fact 'extended edges', meaning that the univariates are not of degree < 2 as polynomials. It therefore makes sense to focus on adding functionality to create univariates of a desired form, either within the test or within the univariate classes. That said, we can discuss other solutions that don't affect performance of the sumcheck prover.
