### ISSUE TITLE
Use Fiat-Shamir in IPA

### ISSUE THREAD

**Issue by codygunton** [AztecProtocol/barretenberg#165]
From: https://github.com/AztecProtocol/barretenberg/pull/31#pullrequestreview-1240637105: the Fiat-Shamir heuristic must be used to generate the round challenges as part of the `ipa_prove` and `ipa_verify` algorithms. The `InnerProductArgument` class should have a `Hash` template parameter that defines which hash algorithm is used.

**Comment by codygunton** [comment]
`IPA::reduce_prove` should have the same interface as `KZG::reduce_prove`. In particular, it should consume a `ProverOutput` of the sort created by `Shplonk::reduce_prove`

**Comment by codygunton** [comment]
Perhaps this was handled in a previous PR? Can't quite recall.

**Comment by adr1anh** [comment]
IPA uses the hash function as the random oracle, which is abstracted away in the Transcript class. 
However, it would be a good idea to parametrize the Transcript for different hash functions later on (Poseidon, Reinforced Concrete, Keccack?)
