### ISSUE TITLE
TODO: Evaluate method for ensuring no zero polynomial in Honk

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#217]
During Honk development, we added a dummy gate in the circuit constructor to ensure we could not encounter a zero polynomial. Determine whether this is acceptable or if there is a better option.

**Comment by codygunton** [comment]
Per Adrian's comment, perhaps we should alter this gate so that all selector values are distinct?

**Comment by codygunton** [comment]
Spawned #423
