### ISSUE TITLE
TODO: Make CommitmentKey take ownership of SRS

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#218]

**Comment by maramihali** [comment]
I think we should also perform any modifications to the SRS (e.g. compute the pippenger point table inside the `CommiterKey` class) to make things more readable. Atm is done under the hood here, when prover/verifier are requesting the monomial points https://github.com/AztecProtocol/barretenberg/blob/mm/ipa/cpp/src/barretenberg/srs/reference_string/file_reference_string.hpp#L43
