### ISSUE TITLE
Divergence between kzg and ipa interface

### ISSUE THREAD

**Issue by arijitdutta67** [AztecProtocol/barretenberg#236]
In PR #205, we get a divergence in the way `ipa` and `kzg` works. In particular, the `commit` function in the `commitment_key` class for `ipa` is not used inside any `ipa` methods, instead we provide the commitment directly to `reduce_prove` and `reduce_verify` as a member of the public input. This is not how the `kzg` interface works.

Also the `pairing_check` method is absent in the `verification_key` class for `ipa`.

 We need to resolve if any issue arises when we interchangeably use `kzg` and `ipa` for bn254 and grumpkin circuits respectively.

_Originally posted by @codygunton in https://github.com/AztecProtocol/barretenberg/pull/205#discussion_r1131120581_

**Comment by arijitdutta67** [comment]
In PR #244, we could resolve the mismatch with `reduce_prove` by introducing the transcript. However the issue with `reduce_verify` still remains (see the conversation [here](https://github.com/AztecProtocol/barretenberg/pull/244#discussion_r1142472758)).

**Comment by maramihali** [comment]
closed by #445
