### ISSUE TITLE
VK hash (sha256) should include the `composer_type`

### ISSUE THREAD

**Issue by dbanks12** [AztecProtocol/barretenberg#261]
I asked @suyash67  if `composer_type` be a part of a VK's hash as it is not included in the sha256. His answer was yes or at least probably yes.

**Comment by suyash67** [comment]
Yes, I think we should add `composer_type`.

Imagine if we have two circuits with the exact same configuration, therefore same `commitments, circuit_size, num_public_inputs` but both use different underlying proof systems (stdhonk and stdplonk for example). In such a case, we would like the vk hash to make the distinction that both circuits are different.

**Comment by suyash67** [comment]
Talked to Zac to confirm this. Zac suggested that we should even add some identifier of chain (for e.g. `sha256("AZTEC_ETHEREUM")`) so that the verification for same circuits across chains could also be unique. But we can do that later.

**Comment by codygunton** [comment]
This was done at some point. Cf #562 -- not sure this is a Barretenberg thing, and I'd like to get rid of various identification enums in favor of using the type system, functions like `std::same_as`, and derived concepts like `HasPlookup` and `IsPlonkFlavor`.
