### ISSUE TITLE
`init_generator_data` crashes when constants are changed

### ISSUE THREAD

**Issue by phated** [AztecProtocol/barretenberg#345]
In #142, @suyash67 changed the constants for `init_generator_data` but when Noir consumed the changes, it caused tests to crash with the stack trace:
```
 thread #2, name = 'tests::noir_integration', stop reason = EXC_BAD_ACCESS (code=2, address=0x16fe00000)
  * frame #0: 0x00000001000ae52c prove_and_verify-5fafba34d1642f00`crypto::generators::init_generator_data() + 244
    frame #1: 0x00000001000b7814 prove_and_verify-5fafba34d1642f00`crypto::generators::get_g1_ladder(unsigned long) + 20
    frame #2: 0x000000010026d010 prove_and_verify-5fafba34d1642f00`acir_format::create_fixed_base_constraint(proof_system::plonk::UltraComposer&, acir_format::FixedBaseScalarMul const&) + 68
    frame #3: 0x000000010022a84c prove_and_verify-5fafba34d1642f00`acir_format::create_circuit(acir_format::acir_format const&, std::__1::unique_ptr<proof_system::ReferenceStringFactory, std::__1::default_delete<proof_system::ReferenceStringFactory> >&&) + 716
    frame #4: 0x000000010028bc54 prove_and_verify-5fafba34d1642f00`acir_proofs::get_total_circuit_size(unsigned char const*) + 164
```

We're reverting these value changes in #338 until the correct fix can be found and applied. This is the tracking issue for finding the core bug.

**Comment by suyash67** [comment]
@phated @vezenovm Can you also please post the exact line at which its giving a bad memory access? I am thinking about this issue and it isn't possible to know the exact cause as I don't know how to run integration tests. Otherwise, can you tell me how can I run the failing test(s)?

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/2592
