### ISSUE TITLE
Add recursion into acir format

### ISSUE THREAD

**Issue by kevaundray** [AztecProtocol/barretenberg#357]
**Problem**

Once [acvm adds the recursion opcode](https://github.com/noir-lang/acvm/issues/198) it will need to be supported by the backend.

**Solution**

We add a recursion field to the `acir_format` and implement the code to handle it. 

This task should be considered complete when we add the relevant code to process a recursion opcode and when we add a test in the test folder to ensure that this works on the cpp side.

**Comment by zac-williamson** [comment]
Working on this in zw/noir-recursion 

Currently I'm implementing recursion where the requirement is the circuit has a _single_ public input. Is this too strict? (if multiple inputs are required, the outer circuit hashes them together).

Doing this makes the UltraPlonk proof data constant-sized, which could help.

I have implemented a Recursion type into `acir_format` with some passing tests, one missing thing is serialisation functions that will be needed by `barretenberg_sys` to turn inner proofs/verification keys into a format that is required by the Recursion constraint.

**Comment by Savio-Sou** [comment]
Closed with https://github.com/AztecProtocol/barretenberg/pull/485.
