### ISSUE TITLE
Visibility in flavor

### ISSUE THREAD

**Issue by codygunton** [AztecProtocol/barretenberg#396]
Everything is public in the flavor classes, but ideally we would not allow directly accessing the underlying array as a means of preventing additional loose coupling.

**Comment by ludamad** [comment]
The backing array will be removed by https://github.com/AztecProtocol/aztec-packages/pull/3277

**Comment by codygunton** [comment]
Resolved by https://github.com/AztecProtocol/aztec-packages/pull/3277
