### ISSUE TITLE
construct_addition_chains is segfaulting again (now for some other reason)

### ISSUE THREAD

**Issue by Rumata888** [AztecProtocol/barretenberg#403]
https://app.circleci.com/pipelines/github/AztecProtocol/barretenberg/2936/workflows/c6aea16a-d353-4f0f-9532-a6d109a17b70/jobs/20611

We've solved a similar issue here:

https://github.com/AztecProtocol/aztec2-internal/issues/1227

but it seems there is another bug and it is even rarer

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/barretenberg/pull/404
