### ISSUE TITLE
barretenberg doesn't work on mac m1

### ISSUE THREAD

**Issue by Ethan-000** [AztecProtocol/barretenberg#41]
Hi,

Barretenberg doesn't seem to work for me at the moment on a mac m1.

I don't know much about c++ but this is possibly an issue related to tbb in the [ultra composer file](https://github.com/AztecProtocol/barretenberg/blob/63c48a11ce5fae3b9d061d5a7c7293f1040bb5be/cpp/src/aztec/plonk/composer/ultra_composer.cpp#L23). As I'm running into this error

```
 Could not find a package configuration file provided by "TBB" with any of
  the following names:
 
    TBBConfig.cmake
    tbb-config.cmake
``` 

after running 

```
./bootstrap.sh
```

After running,

```
brew install tbb
```

the error turned into this

```
fatal error: 'tbb/atomic.h' file not found
#include <tbb/atomic.h>
```

**Comment by iAmMichaelConnor** [comment]
Hi @Ethan-000 - if you're working with Noir, there's a separate barretenberg repo here which Noir uses as its bberg dependency: https://github.com/noir-lang/aztec-connect which should be more stable.

The code in this repo (especially the `master` branch) is under rapid development and doesn't currently have technical support.
