### ISSUE TITLE
Couldn't setup the project

### ISSUE THREAD

**Issue by BZAghalarov** [AztecProtocol/barretenberg#449]
Hi,

I am using Ubuntu 20.04.1, Linux operation system
I am trying to setup the project as it is listed [here.](https://github.com/AztecProtocol/barretenberg/#dependencies) 
Successfully run the below 2 comands:

- `sudo apt-get install cmake clang clang-format ninja-build binaryen`
- `sudo apt-get install libomp-dev`
The 3rd command which suggests running `sh` script returns an error.
Do I need to run other specific script for generating the requested file - `/barretenberg/cpp/default" does not exist`
![image](https://github.com/AztecProtocol/barretenberg/assets/17585937/2a1907b0-d648-4a10-bc2e-7e550afa2559)

**Comment by phated** [comment]
`default` is the preset that is being run. Does your version of cmake not have access to presets? According to their docs at https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html, they were added in 3.19

**Comment by BZAghalarov** [comment]
Thanks for answering.
After your comment, I checked `cmake` version and it was `3.16`. 
As mentioned [here](https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line) my OS repositories are not updated that's why cmake installed the old version.

> The most common situation is when you want to install the latest version of cmake, but your Operating System's repositories are not updated. For example, in my case, I have a laptop running Ubuntu 16.04, and when I executed the command sudo apt install cmake the installed version was 3.5.1; instead of 3.25.1 which is the current version at [cmake.org](https://www.cmake.org/download).

I uninstall it and reinstalled version 3.26 because it was [required](https://github.com/AztecProtocol/barretenberg#dependencies) to use `cmake >= 3.24` and my problem is solved for now.

Maybe it is a good idea to push it to install >=3.19 rather than the suggested version.

**Comment by phated** [comment]
cmake 3.24 is required for other cmake features, so that is the recommended version.
