### ISSUE TITLE
IPA and work queue interaction

### ISSUE THREAD

**Issue by maramihali** [AztecProtocol/barretenberg#479]
Currently to unify the pcs interfaces we don't use the work_queue for openings - once the future of work_queue (or its successor) is decided it might be worth thinking how to integrate more parallelisation in the IPA so both KZG and IPA openings can benefit from it.

**Comment by codygunton** [comment]
The work queue was removed in https://github.com/AztecProtocol/aztec-packages/pull/2814

**Comment by Rumata888** [comment]
Parallelized in https://github.com/AztecProtocol/aztec-packages/pull/3882
