### ISSUE TITLE
Spike: how hard is it to implement a DummyComposer?

### ISSUE THREAD

**Issue by dbanks12** [AztecProtocol/barretenberg#496]
This has become more relevant in light of the recent API conversations. It would be great if aztec circuits didn't have to rely on crypto/ecc/etc functions and types outside the stdlib.

Does the Composer / CircuitConstructor separation affect this at all?

@suyash67 looked into this previously and we determined that it was too hard (for the moment at least).

Please discuss and let's come to a conclusion whether this is feasible.

**Comment by codygunton** [comment]
Spike finished: the project was abandoned when it was decided that the core protocol circuits would be written in Noir. It could be picked up again though--in particular, it would be nice if the recursive verifiers were the only verifiers, but a simulator offered a fast execution mode.
