### ISSUE TITLE
UltraHonk on Grumpkin

### ISSUE THREAD

**Issue by maramihali** [AztecProtocol/barretenberg#636]
This requires templating the `plookup_tables` folder so that the`UltraCircuitBuilder` can work on Grumpkin and have the `UltraGrumpkin` flavor use  Grumpkin + IPA.

**Comment by maramihali** [comment]
**if** we decide we will need UltraHonk on Grumpkin

**Comment by codygunton** [comment]
We don't need this. If we did decide to take a Halo2-style approach, we would likely use the standard arithmetization anyway.
