### ISSUE TITLE
Pow polynomial definition? Use evaluation form to get the pow perturbation?

### ISSUE THREAD

**Issue by codygunton** [AztecProtocol/barretenberg#686]

**Comment by maramihali** [comment]
Plan is to implement the perturbation polynomial in evaluation form. Prover will send evaluations to Verifier and they will use barycentric evaluation to evaluate the polynomial at random point `alpha`.

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/2624
