### ISSUE TITLE
General goblin-ized group operations

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#707]
Currently, the only "goblinized" group operation is `batch_mul`, i.e. one cannot perform goblin-arithmetized group operations via `P = Q * R`, `P += Q * z`, etc. At some point it may be convenient to allow for more general operations like the aforementioned but this would have a large footprint in biggroup and could be error prone. In principle, all operations can be written as batch muls but this may be inefficient if a multiply-then-accumulate operation is used when a simple add-accumulate is sufficient, e.g. in an expression like $P = P_0 + \alpha*P_1 + \alpha^2*P_2$ which arises frequently.

**Comment by ameya-deshmukh** [comment]
@ledwards2225 can I take this up?

**Comment by ledwards2225** [comment]
> @ledwards2225 can I take this up?

@ameya-deshmukh The code relevant to this issue is very much in flux and it's not clear that we want what it describes so this might not be the right place to start. That said, we appreciate your interest in contributing, and if you'd like we can give it some thought and make suggestions for other issues that might be better.

**Comment by ameya-deshmukh** [comment]
Sure! Is there an issue which could be better served by me in your opinion? I'm fair game to anything😁

**Comment by ledwards2225** [comment]
@ameya-deshmukh I'll give it some thought and get back to you soon

**Comment by ledwards2225** [comment]
This work isn't planned. No use case in the foreseeable future.
