### ISSUE TITLE
Find a way to reduce verbosity in flavor classes

### ISSUE THREAD

**Issue by ludamad** [AztecProtocol/barretenberg#766]
My main idea here is to have a small .yaml file format that specifies the structure of our witnesses and precomputed polynomials, what functionality and backing they have etc and generates plain the flavor classes. This has tradeoffs:
Pro:
- We can flexibly generate the methods that do finnicky things that reference every member.
- We can potentially generate non-templated classes and speed up compile time.
Cons:
- The generated product will (probably) be more verbose.
- Overhead of thinking about this YAML=>CPP generation

OTHER IDEAS TO REDUCE VERBOSITY
- Namely composition. Will continue to think on this

**Comment by codygunton** [comment]
We went in the OTHER IDEAS direction
