### ISSUE TITLE
ECCVM: properly handle transcript polynomial univariate evaluations

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#768]
The ECCVM needs to open the five ECC op transcript polynomials as univariates so consistency can be established in the Translator. This was overlooked in the original implementation. For now, we've introduced a new round to the ECCVM protocol that establishes a batched univariate opening claim for this purpose. This is inefficient in that it requires an entirely separate IPA opening protocol. Ideally we would find a way to batch everything into one IPA opening which may require shplonk.

Note: IPA cannot handle polynomials for which the latter half of the coefficients are 0. This arises in general for our transcript polynomials since the ECCVM has a large fixed size that may not be fully utilized. To get around this we simply batch the constant polynomial 1 in with the other 5. This is likely not a long term solution.

**Comment by maramihali** [comment]
Benchmark for native IPA
![image](https://github.com/AztecProtocol/barretenberg/assets/33263352/f060a8d0-2161-4e96-b205-c8eee81f78c6)

**Comment by maramihali** [comment]
Idea to avoid two IPA openings without reviving Shplonk: https://hackmd.io/_dcQgfPjTPutOopViZLv-Q

**Comment by maramihali** [comment]
https://github.com/AztecProtocol/aztec-packages/pull/7164 removes the need for a second opening but we still need the `hack_polynomial` for IPA to work.
