### ISSUE TITLE
ECCVM receives/hashes transcript commitments

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#770]
@Rumata888 pointed out that the ECCVM should receive and hash the four aggregate transcript column commitments $[T_j], j = 0,1,2,3$. These are output as part of the proof of the final merge protocol. Need to determine the correct way to do this. Public inputs?

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/3433
