### ISSUE TITLE
Mock App function circuits in Goblin recursion tests

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#803]
The real kernel circuit will perform two recursive verifications (eventually, folding verifications). Currently we don't have a mocked app circuit at all in the goblin recursion tests so we simply construct two recursive verifications of the previous kernel proof as a stand in approximation. We need to actually construct an app proof since that will be a significant computation. For our purposes the app proof can simply be a circuit of given size comprised entirely of arithmetic gates.

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/4242
