### ISSUE TITLE
Investigate acir tests where varnum != witness.size()

### ISSUE THREAD

**Issue by ludamad** [AztecProtocol/barretenberg#815]

**Comment by ledwards2225** [comment]
I would think that `varnum == witness.size()` (possibly with an offset by 1 due to 0 const hacks) but this is not at all the case. See for example `TestVarKeccak`. What's going on?

**Comment by ludamad** [comment]
<img width="669" alt="Screenshot 2023-12-18 at 4 41 55 PM" src="https://github.com/AztecProtocol/barretenberg/assets/163993/41c9b7ee-77bf-438b-b808-168c58e129a2">
seems to be the other acir opcodes, we will revisit this post break

**Comment by ledwards2225** [comment]
Explanation: `witness_values` is the array of witnesses known to noir at the time of acir generation. This may be less than `varnum` which is the number of witnesses known to exist by noir, even if the values themselves are not known.
