### ISSUE TITLE
Integrate ecc ops and databus into check_circuit

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#842]
`check_circuit()` is incomplete for the UltraGoblinCircuitBuilder because it does not check the goblin ecc op gates or the databus lookup gates. For this reason, various tests utilizing the UG arithmetization must construct and verify full proofs to be complete.

Note: Its not clear what this should look like for goblin ecc ops since UGH only checks two things here: that the ecc op wire columns match the wire values at the start of the exec trace, and also that the ecc op wires are zero outside of that block. Neither of these checks really make sense at the builder stage since this structure doesn't arise until the Composer stage. Still, there may be some basic sanity checks to be performed.

Edit: expanding on my previous comments above:

For Goblin ecc ops: There's nothing to check here. The only structure imposed by the UGH proof is that introduced in the "composer" stage, i.e. the duplication of the ecc op wires across columns. Checking the correctness of the underlying ops would be misleading since invalid ops would not cause verification of the UGH proof to fail. 

For databus lookups: We cant check the actual databus lookup relation since it depends on polynomials computed by the prover (similar to the conventional lookup relation). We currently check conventional lookups in CircuitChecker by simply ensuring that the lookup gates are present in the set of tables used in the circuit. (See e.g. `LookupHashTable`). We could do something similar for the databus: check that the "read" gates contain data present in the databus columns.

**Comment by maramihali** [comment]
From discussion with @ledwards2225 makes sense to do this when work on databus has been completed since there might be changes to the current structure (e.g. we might have multiple calldata columns) so moving to Next Up
