### ISSUE TITLE
Investigate GoblinTranslatorComposerTests.Basic for "Trying to invert zero in the field"

### ISSUE THREAD

**Issue by lucasxia01** [AztecProtocol/barretenberg#847]
Failed test: https://app.circleci.com/pipelines/github/AztecProtocol/aztec-packages/23912/workflows/c740ba18-ba8b-41ae-ae8c-b4c2b1956786/jobs/1105985

However, rerunning it in CI and running it locally yields no issues.

**Comment by ledwards2225** [comment]
I've seen similar behavior. Some details in the latest comment in #819

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/4751 unclosed by https://github.com/AztecProtocol/aztec-packages/pull/5174 and then closed again by https://github.com/AztecProtocol/aztec-packages/pull/5189
