### ISSUE TITLE
IPA verifier is O(nlogn)

### ISSUE THREAD

**Issue by lucasxia01** [AztecProtocol/barretenberg#857]
We currently inefficiently compute G^(0) in nlogn time where n is the length of the polynomial. 

We can reduce this to to O(n) time by precomputing coefficients, which should be also parallelizable.

**Comment by zac-williamson** [comment]
fixed in https://github.com/AztecProtocol/aztec-packages/pull/9420

**Comment by lucasxia01** [comment]
Closed by above PR
