### ISSUE TITLE
Transcript can't handle the point at infinity

### ISSUE THREAD

**Issue by Rumata888** [AztecProtocol/barretenberg#866]
Currently if we submit the point at infinity to the transcript, it will not detect the issue and will store a malformed representation of the point, leading to errors down the line

**Comment by codygunton** [comment]
@maramihali your assessment of this? is the issue handled?

**Comment by maramihali** [comment]
yes

**Comment by maramihali** [comment]
with the mention that during the audit we need to have additional testing - https://github.com/AztecProtocol/barretenberg/issues/1064
