### ISSUE TITLE
Reinstate flexibility in use of Relations

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#916]
It is often useful to consider only a subset of relations when running certain tests. This used to be possible by simply commenting out specific relations in the relevant Flavor class. With the introduction of protogalaxy, there are numerous static asserts and hard coded magic numbers that make it so the code will not even build if the relations change. 

By extension, this will also create a lot of pain for the next person who goes to add or update a relation, particularly if the max relation length stats change. It's nice to have tests that indicate important changes, but they should simply fail at runtime, not prevent building altogether. It should also not be the responsibility of someone adding a relation to go into a bunch of hard coded tests and update them accordingly.

**Comment by codygunton** [comment]
@ledwards2225 I think we have this now, don't we? I feel like I successfully commented out some relations and maybe a single `static_assert` back during my spike on homogeneous Protogalaxy and was able to work in that limited setting.

**Comment by ledwards2225** [comment]
> [@ledwards2225](https://github.com/ledwards2225) I think we have this now, don't we? I feel like I successfully commented out some relations and maybe a single `static_assert` back during my spike on homogeneous Protogalaxy and was able to work in that limited setting.

Its still broken but I'm not that concerned about it. Its only annoying if you want to comment out the Perm relation since that's the highest degree one. Certain test suites will build without much issue but others require commenting out of 3 or 4 different tests because they contain compile time checks of that max length which I guess must be hard coded and not determined at compile time.

**Comment by ledwards2225** [comment]
not critical
