### ISSUE TITLE
Pairing-input aggregation in Honk recursive verifier

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#934]
The Honk recursive verifier is incomplete in the sense that there is no logic for "accumulating" the set of G1 points that constitute the input to a pairing check, i.e. the output of a previous recursive verification. This logic exists for Plonk so we can take inspiration from what's done there, although as usual I suspect there's room for improvement. 

Note: One potential wrinkle just occurring to me now is that with Plonk, the G2 points in the pairing are always the same; with Honk, these points depend on the size of the circuit since the degree check will differ. Hopefully there's a simple way to handle this but it needs some thought.

**Comment by maramihali** [comment]
This is an issue relevant for the RollupIVC milestone as well https://github.com/AztecProtocol/barretenberg/milestone/10 but apparently I cannot add two milestones :-? Another thing that occurred to me is that we (might) need to accumulate the pairings from the merge recursive verifiers as well

**Comment by lucasxia01** [comment]
Duplicate of https://github.com/AztecProtocol/barretenberg/issues/1059.
