### ISSUE TITLE
Coordinate with Sasha regarding Standard arithmetization

### ISSUE THREAD

**Issue by ledwards2225** [AztecProtocol/barretenberg#935]
AFAIK all of Sasha's work has been built around the StandardCircuitBuilder. We need to figure out how to proceed so as not to disrupt. Presumably he doesn't care about proving system level stuff so maybe this just amounts to keeping Standard around (without a corresponding proving system). Figure out the best path here.

**Comment by codygunton** [comment]
We'll just keep this around for now. There is no need to have a proving system that supports the circuit builder in order for the SMT work to continue.
