### ISSUE TITLE
Recursive verification for TranslatorRecursiveVerifier::verifiy_translation()

### ISSUE THREAD

**Issue by maramihali** [AztecProtocol/barretenberg#986]

**Comment by codygunton** [comment]
@maramihali please expand

**Comment by maramihali** [comment]
This is included in: https://github.com/AztecProtocol/barretenberg/issues/991. We have unconstrained `from_witness` calls in the goblin recursive verifier to construct the  TranslationEvaluations input to `verify_translation`.
